### ISSUE TITLE
关于变量替换list的问题

### ISSUE THREAD

**Issue by wuxiongliu1** [bbossgroups/bboss-elastic#2]
现在有个参数的数据是List类型的，然后数据内容为[“qunar”,"lvmama"],但是在esmapper 文件中替换出来的结果是：

```
terms": {
                    "source": [ctrip, qunar]
                  }
```
可以看到ctrip 和qunar未加上双引号，我的变量替换的写法如下
```
{
                  "terms": {
                    "source": #[sourceList]
                  }
                }
```
这个问题是什么原因呢，我该怎么写才能够让列表中的变量有双引号？麻烦大牛帮忙解答一下，谢谢了

**Comment by yin-bp** [comment]
可以通过foreach循环来实现：
` #if($sourceList && $sourceList.size() > 0)  ##如果设置了sourceList，才拼接source检索条件
  {"terms": {
       "source": [
              #foreach($source in $sourceList)
                #if($velocityCount > 0),#end "$source"
              #end
              ]

  }}
  #end`

**Comment by wuxiongliu1** [comment]
恩，好的，谢谢了
