### ISSUE TITLE
新版本和spring boot 的集成的问题

### ISSUE THREAD

**Issue by wuxiongliu1** [bbossgroups/bboss-elastic#3]
关注作者开发的bboss框架，有新的集成spring boot  的版本。将es 的配置配置在application.properties文件中，但是因为我们公司的约定规范：application.properties 文件是放在resources目录的config目录下，发现当application.properties 文件在此目录的时候，es的配置就不生效。这个可以通过什么办法解决呢？

**Comment by yin-bp** [comment]
目前没有办法解决你提出的问题，替代方法:
将bboss相关的配置放到独立的配置文件中，改配置文件对应的路径和名称为conf/elasticsearch.properties

**Comment by yin-bp** [comment]
已经在5.0.6.3版本中增加config/application.properties文件的支持

**Comment by wuxiongliu1** [comment]
好的，非常感谢了
