### ISSUE TITLE
基于spring boot 的配置，能否支持spring的profiles

### ISSUE THREAD

**Issue by wuxiongliu1** [bbossgroups/bboss-elastic#4]
在开发的是时候一般会有dev 与production 两个profiles的配置；也所以相应的配置文件会有两份application-dev.properties; application-production.properties 两个配置文件；而现在的的es 的配置只支持放在application.properties 文件里；能否支持根据spring的profile配置切换生产的与测试的es 配置呢？

**Comment by yin-bp** [comment]
正在规划实现中

**Comment by yin-bp** [comment]
5.0.7.8版本及后续版本都已经支持spring booter的profile机制了，参考文档：

https://my.oschina.net/bboss/blog/1835601
